name: Sealog Client Vehicle 

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /opt/sealog-client-Sub
    
    steps:
    - name: Debug Runner Info 
      run: |
        echo "Runner name: ${{ runner.name }}"
        echo "Runner OS: ${{ runner.os }}"
        echo "Runner arch: ${{ runner.arch }}"
        echo "Workflow name: ${{ github.workflow }}"
        echo "Event name: ${{ github.event_name }}"
        echo "Branch name: ${{ github.ref }}"
        echo "GitHub workspace: ${{ github.workspace }}"
        echo "Current directory: $(pwd)"
        ls -la

    - name: Navigate to project directory and update
      run: |
        git fetch --all
        git checkout ${{ github.ref_name }}
        git pull origin ${{ github.ref_name }}
        echo "Current directory: $(pwd)"
        ls -la

    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          echo "package-lock.json not found, falling back to npm install"
          npm install
        fi

    - name: Run linter
      continue-on-error: true
      run: |
        npm run lint > lint_report.txt || true
        echo "Linting issues found:"
        cat lint_report.txt

    - name: Upload lint report
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: lint_report.txt

    - name: Build project
      run: npm run build
      
    - name: Error logging
      if: failure()
      run: |
        echo "Job failed. Logging additional information:"
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "Git version: $(git --version)"
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Git status:"
        git status
        echo "Git log (last 5 commits):"
        git log -n 5 --oneline

    - name: Success logging
      if: success()
      run: |
        echo "Build completed successfully!"
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "Git version: $(git --version)"
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -lah
        echo "Git status:"
        git status
        echo "Git log (last 5 commits):"
        git log -n 5 --oneline